# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search_ml.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'search_ml.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsearch_ml.proto\x12\tsearch_ml\">\n\x08\x44ocument\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x17\n\x0f\x63ontent_snippet\x18\x03 \x01(\t\"E\n\x0bRankRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\'\n\ncandidates\x18\x02 \x03(\x0b\x32\x13.search_ml.Document\"+\n\x0eRankedDocument\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\":\n\x0cRankResponse\x12*\n\x07results\x18\x01 \x03(\x0b\x32\x19.search_ml.RankedDocument\" \n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"#\n\x11\x45mbeddingResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32\x91\x01\n\tMLService\x12\x39\n\x06ReRank\x12\x16.search_ml.RankRequest\x1a\x17.search_ml.RankResponse\x12I\n\x0cGetEmbedding\x12\x1b.search_ml.EmbeddingRequest\x1a\x1c.search_ml.EmbeddingResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_ml_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_DOCUMENT']._serialized_start=30
  _globals['_DOCUMENT']._serialized_end=92
  _globals['_RANKREQUEST']._serialized_start=94
  _globals['_RANKREQUEST']._serialized_end=163
  _globals['_RANKEDDOCUMENT']._serialized_start=165
  _globals['_RANKEDDOCUMENT']._serialized_end=208
  _globals['_RANKRESPONSE']._serialized_start=210
  _globals['_RANKRESPONSE']._serialized_end=268
  _globals['_EMBEDDINGREQUEST']._serialized_start=270
  _globals['_EMBEDDINGREQUEST']._serialized_end=302
  _globals['_EMBEDDINGRESPONSE']._serialized_start=304
  _globals['_EMBEDDINGRESPONSE']._serialized_end=339
  _globals['_MLSERVICE']._serialized_start=342
  _globals['_MLSERVICE']._serialized_end=487
# @@protoc_insertion_point(module_scope)
