// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/search_ml.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ContentSnippet string                 `protobuf:"bytes,3,opt,name=content_snippet,json=contentSnippet,proto3" json:"content_snippet,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_search_ml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_ml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_search_ml_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetContentSnippet() string {
	if x != nil {
		return x.ContentSnippet
	}
	return ""
}

type RankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`           // search string
	Candidates    []*Document            `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"` // n documents to reorder
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankRequest) Reset() {
	*x = RankRequest{}
	mi := &file_proto_search_ml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankRequest) ProtoMessage() {}

func (x *RankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_ml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankRequest.ProtoReflect.Descriptor instead.
func (*RankRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_ml_proto_rawDescGZIP(), []int{1}
}

func (x *RankRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RankRequest) GetCandidates() []*Document {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type RankedDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"` // relevance score from 0 to 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankedDocument) Reset() {
	*x = RankedDocument{}
	mi := &file_proto_search_ml_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankedDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankedDocument) ProtoMessage() {}

func (x *RankedDocument) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_ml_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankedDocument.ProtoReflect.Descriptor instead.
func (*RankedDocument) Descriptor() ([]byte, []int) {
	return file_proto_search_ml_proto_rawDescGZIP(), []int{2}
}

func (x *RankedDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RankedDocument) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RankedDocument      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // n documents sorted by score.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankResponse) Reset() {
	*x = RankResponse{}
	mi := &file_proto_search_ml_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankResponse) ProtoMessage() {}

func (x *RankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_ml_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankResponse.ProtoReflect.Descriptor instead.
func (*RankResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_ml_proto_rawDescGZIP(), []int{3}
}

func (x *RankResponse) GetResults() []*RankedDocument {
	if x != nil {
		return x.Results
	}
	return nil
}

type EmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	mi := &file_proto_search_ml_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_ml_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_ml_proto_rawDescGZIP(), []int{4}
}

func (x *EmbeddingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"` // k dimensional embedding vector
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_proto_search_ml_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_ml_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_ml_proto_rawDescGZIP(), []int{5}
}

func (x *EmbeddingResponse) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

var File_proto_search_ml_proto protoreflect.FileDescriptor

const file_proto_search_ml_proto_rawDesc = "" +
	"\n" +
	"\x15proto/search_ml.proto\x12\tsearch_ml\"Y\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12'\n" +
	"\x0fcontent_snippet\x18\x03 \x01(\tR\x0econtentSnippet\"X\n" +
	"\vRankRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x123\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x13.search_ml.DocumentR\n" +
	"candidates\"6\n" +
	"\x0eRankedDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\"C\n" +
	"\fRankResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.search_ml.RankedDocumentR\aresults\"&\n" +
	"\x10EmbeddingRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"+\n" +
	"\x11EmbeddingResponse\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector2\x91\x01\n" +
	"\tMLService\x129\n" +
	"\x06ReRank\x12\x16.search_ml.RankRequest\x1a\x17.search_ml.RankResponse\x12I\n" +
	"\fGetEmbedding\x12\x1b.search_ml.EmbeddingRequest\x1a\x1c.search_ml.EmbeddingResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_search_ml_proto_rawDescOnce sync.Once
	file_proto_search_ml_proto_rawDescData []byte
)

func file_proto_search_ml_proto_rawDescGZIP() []byte {
	file_proto_search_ml_proto_rawDescOnce.Do(func() {
		file_proto_search_ml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_ml_proto_rawDesc), len(file_proto_search_ml_proto_rawDesc)))
	})
	return file_proto_search_ml_proto_rawDescData
}

var file_proto_search_ml_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_search_ml_proto_goTypes = []any{
	(*Document)(nil),          // 0: search_ml.Document
	(*RankRequest)(nil),       // 1: search_ml.RankRequest
	(*RankedDocument)(nil),    // 2: search_ml.RankedDocument
	(*RankResponse)(nil),      // 3: search_ml.RankResponse
	(*EmbeddingRequest)(nil),  // 4: search_ml.EmbeddingRequest
	(*EmbeddingResponse)(nil), // 5: search_ml.EmbeddingResponse
}
var file_proto_search_ml_proto_depIdxs = []int32{
	0, // 0: search_ml.RankRequest.candidates:type_name -> search_ml.Document
	2, // 1: search_ml.RankResponse.results:type_name -> search_ml.RankedDocument
	1, // 2: search_ml.MLService.ReRank:input_type -> search_ml.RankRequest
	4, // 3: search_ml.MLService.GetEmbedding:input_type -> search_ml.EmbeddingRequest
	3, // 4: search_ml.MLService.ReRank:output_type -> search_ml.RankResponse
	5, // 5: search_ml.MLService.GetEmbedding:output_type -> search_ml.EmbeddingResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_search_ml_proto_init() }
func file_proto_search_ml_proto_init() {
	if File_proto_search_ml_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_ml_proto_rawDesc), len(file_proto_search_ml_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_ml_proto_goTypes,
		DependencyIndexes: file_proto_search_ml_proto_depIdxs,
		MessageInfos:      file_proto_search_ml_proto_msgTypes,
	}.Build()
	File_proto_search_ml_proto = out.File
	file_proto_search_ml_proto_goTypes = nil
	file_proto_search_ml_proto_depIdxs = nil
}
